server:
  port: 8083

spring:
  application:
    name: user-service

eureka:
    instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 5
      metadataMap:
        instanceId: "${spring.application.name}:${random.value}"
